# Generated by Django 4.2.9 on 2024-01-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_time',
        ),
    ]
