# Generated by Django 4.2.9 on 2024-01-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='https://react.semantic-ui.com/images/image-16by9.png', upload_to='images/'),
        ),
    ]
